### ISSUE TITLE
src/scaler.cpp:297:7: error: non-floating-point argument in call to function '__builtin_isnan'

### ISSUE THREAD

**Issue by picca** [PierreRaybaut/guiqwt#60]
Hello, I got this report bug

Package: guiqwt
Version: 3.0.2-1
Severity: important
User: debian-glibc@lists.debian.org
Usertags: 2.23

This package fails to build with libc6 2.23 (2.23-0experimental0 from
experimental).

> sbuild (Debian sbuild) 0.68.0 (15 Jan 2016) on dl580gen9-02.hlinux
...
> compiling C++ sources
> C compiler: c++ -pthread -DNDEBUG -g -fwrapv -O2 -Wall -fno-strict-aliasing -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC
> 
> compile options: '-I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c'
> extra options: '-Wall'
> c++: src/scaler.cpp
> In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1777:0,
>                  from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:18,
>                  from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
>                  from src/scaler.cpp:11:
> /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
>  #warning "Using deprecated NumPy API, disable it by " \
>   ^
> src/scaler.cpp: In function 'bool scale_src_dst_interp(Params&, PixelScale&, Interp&)':
> src/scaler.cpp:418:45: warning: typedef 'Transform' locally defined but not used [-Wunused-local-typedefs]
>      typedef typename Params::transform_type Transform;
>                                              ^
> In file included from /usr/include/python2.7/pyport.h:325:0,
>                  from /usr/include/python2.7/Python.h:58,
>                  from src/scaler.cpp:8:
> src/scaler.cpp: In instantiation of 'void _scale_rgb(DEST&, Array2D<ST>&, const Scale&, const Trans&, int, int, int, int, Interpolation&) [with DEST = Array2D<unsigned int>; ST = long unsigned int; Scale = LutScale<long unsigned int, unsigned int>; Trans = XYTransform<Array1D<double> >; Interpolation = NearestInterpolation<long unsigned int, XYTransform<Array1D<double> > >]':
> src/scaler.cpp:423:15:   required from 'bool scale_src_dst_interp(Params&, PixelScale&, Interp&) [with Params = params<XYTransform<Array1D<double> > >; PixelScale = LutScale<long unsigned int, unsigned int>; Interp = NearestInterpolation<long unsigned int, XYTransform<Array1D<double> > >]'
> src/scaler.cpp:447:58:   required from 'bool scale_src_dst(Params&, PixelScale&) [with Params = params<XYTransform<Array1D<double> > >; PixelScale = LutScale<long unsigned int, unsigned int>]'
> src/scaler.cpp:501:42:   required from 'bool scale_src_bw(Params&) [with Params = params<XYTransform<Array1D<double> > >; ST = long unsigned int]'
> src/scaler.cpp:560:38:   required from 'PyObject* dispatch_source(Params&) [with Params = params<XYTransform<Array1D<double> > >; PyObject = _object]'
> src/scaler.cpp:641:48:   required from here
> src/scaler.cpp:297:7: error: non-floating-point argument in call to function '__builtin_isnan'
>    if (isnan(val)) {
>        ^
> src/scaler.cpp: In instantiation of 'void _scale_rgb(DEST&, Array2D<ST>&, const Scale&, const Trans&, int, int, int, int, Interpolation&) [with DEST = Array2D<unsigned int>; ST = long unsigned int; Scale = LutScale<long unsigned int, unsigned int>; Trans = XYTransform<Array1D<double> >; Interpolation = SubSampleInterpolation<long unsigned int, XYTransform<Array1D<double> > >]':
> src/scaler.cpp:423:15:   required from 'bool scale_src_dst_interp(Params&, PixelScale&, Interp&) [with Params = params<XYTransform<Array1D<double> > >; PixelScale = LutScale<long unsigned int, unsigned int>; Interp = SubSampleInterpolation<long unsigned int, XYTransform<Array1D<double> > >]'
> src/scaler.cpp:453:56:   required from 'bool scale_src_dst(Params&, PixelScale&) [with Params = params<XYTransform<Array1D<double> > >; PixelScale = LutScale<long unsigned int, unsigned int>]'
> src/scaler.cpp:501:42:   required from 'bool scale_src_bw(Params&) [with Params = params<XYTransform<Array1D<double> > >; ST = long unsigned int]'
> src/scaler.cpp:560:38:   required from 'PyObject* dispatch_source(Params&) [with Params = params<XYTransform<Array1D<double> > >; PyObject = _object]'
> src/scaler.cpp:641:48:   required from here
> src/scaler.cpp:297:7: error: non-floating-point argument in call to function '__builtin_isnan'
> src/scaler.cpp: In instantiation of 'void _scale_rgb(DEST&, Array2D<ST>&, const Scale&, const Trans&, int, int, int, int, Interpolation&) [with DEST = Array2D<unsigned int>; ST = long unsigned int; Scale = LutScale<long unsigned int, unsigned int>; Trans = XYTransform<Array1D<double> >; Interpolation = LinearInterpolation<long unsigned int, XYTransform<Array1D<double> > >]':
> src/scaler.cpp:423:15:   required from 'bool scale_src_dst_interp(Params&, PixelScale&, Interp&) [with Params = params<XYTransform<Array1D<double> > >; PixelScale = LutScale<long unsigned int, unsigned int>; Interp = LinearInterpolation<long unsigned int, XYTransform<Array1D<double> > >]'
> src/scaler.cpp:457:57:   required from 'bool scale_src_dst(Params&, PixelScale&) [with Params = params<XYTransform<Array1D<double> > >; PixelScale = LutScale<long unsigned int, unsigned int>]'
> src/scaler.cpp:501:42:   required from 'bool scale_src_bw(Params&) [with Params = params<XYTransform<Array1D<double> > >; ST = long unsigned int]'
> src/scaler.cpp:560:38:   required from 'PyObject* dispatch_source(Params&) [with Params = params<XYTransform<Array1D<double> > >; PyObject = _object]'
> src/scaler.cpp:641:48:   required from here
> src/scaler.cpp:297:7: error: non-floating-point argument in call to function '__builtin_isnan'
> src/scaler.cpp: In instantiation of 'void _scale_rgb(DEST&, Array2D<ST>&, const Scale&, const Trans&, int, int, int, int, Interpolation&) [with DEST = Array2D<float>; ST = long unsigned int; Scale = LinearScale<long unsigned int, float>; Trans = XYTransform<Array1D<double> >; Interpolation = NearestInterpolation<long unsigned int, XYTransform<Array1D<double> > >]':
> src/scaler.cpp:423:15:   required from 'bool scale_src_dst_interp(Params&, PixelScale&, Interp&) [with Params = params<XYTransform<Array1D<double> > >; PixelScale = LinearScale<long unsigned int, float>; Interp = NearestInterpolation<long unsigned int, XYTransform<Array1D<double> > >]'
> src/scaler.cpp:447:58:   required from 'bool scale_src_dst(Params&, PixelScale&) [with Params = params<XYTransform<Array1D<double> > >; PixelScale = LinearScale<long unsigned int, float>]'
> src/scaler.cpp:510:41:   required from 'bool scale_src_bw(Params&) [with Params = params<XYTransform<Array1D<double> > >; ST = long unsigned int]'
> src/scaler.cpp:560:38:   required from 'PyObject* dispatch_source(Params&) [with Params = params<XYTransform<Array1D<double> > >; PyObject = _object]'
> src/scaler.cpp:641:48:   required from here
> src/scaler.cpp:297:7: error: non-floating-point argument in call to function '__builtin_isnan'
...

-- 
Martin Michlmayr
Linux for HPE Helion, Hewlett Packard Enterprise

**Comment by PierreRaybaut** [comment]
Should be fixed with revision 63374ce, but I'm not able to reproduce the issue right now and to be sure that it's fixed.
